
project_id = "yifimiqeybttmbhuplaq"

# Enable better console logging and debugging
[functions]
debug = true

# Set database timeouts for better offline handling
[database]
timeout = 15

# Improve network resilience for offline scenarios
[api]
request_timeout = 30
