
project_id = "yifimiqeybttmbhuplaq"

# Enable better console logging and debugging
[functions]
debug = true

# Set database timeouts for better offline handling
[database]
timeout = 30  # Increased from 15

# Improve network resilience for offline scenarios
[api]
request_timeout = 45  # Increased from 30
max_retries = 3  # Add retry mechanism

