
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yifimiqeybttmbhuplaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZmltaXFleWJ0dG1iaHVwbGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDYwNjYsImV4cCI6MjA1OTk4MjA2Nn0.LoMhbECAQxEuf3o35XbFmps5v1-iZ4JieXstrsmylYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to send a refresh signal through Supabase
export const sendKioskRefreshSignal = async (restaurantId: string) => {
  try {
    console.log(`Sending kiosk refresh signal for restaurant: ${restaurantId}`);
    
    // Insert a record into the kiosk_refresh_signals table that kiosks can listen to
    const { data, error } = await supabase
      .from('kiosk_refresh_signals')
      .insert({
        restaurant_id: restaurantId,
        timestamp: new Date().toISOString()
      });
    
    if (error) {
      console.error('Error inserting kiosk refresh signal:', error);
      throw error;
    }
    
    console.log('Successfully inserted kiosk refresh signal:', data);
    return true;
  } catch (error) {
    console.error('Error sending kiosk refresh signal:', error);
    return false;
  }
};
